language: node_js
node_js:
- 8
sudo: required
cache:
  directories:
  - node_modules
script:
- yarn lint
- yarn build
- yarn test
deploy:
  provider: npm
  email: ebuccaneer@gmx.at
  api_key:
    secure: Qy64rtSPk8YqfkwvGNRIEyshBsipDRGPiFOoXNKkpK2T5a88+JjkCtyHoo0n/lqkH2PWuZ+Nj+FCzZNgT+UC/o6eRpBEMr2VnM60WmgA7TeQal6ScuzXQt8jkvTq2MIeDjBIbZ2sOTEKKf/63unz7uheJAksSRIM67ZKNzN8Js9Zq6Qev70hpXsOeQ1bZU22o8VUy1W2lLQohUWxMz6W3lSCicb42phsfwiVJObgZXrwQFOrZZHaXlCWfHu4kVlP8jN69IRaJPLSj0t4ZMx4JTQYAGiDhJiXWZR1u6oBGBkOcKn77wCnDVuqB2KfuFklaqXUNux0r0xUMPgz1TLjqpbmzcePXxEiS27IvpALcxba0tPjB22IeIg7Woh0PwmEUXMCvIwvN1ka235ychXo5jApTa088kn8IOGUHgkIWWe5RbKbTeFyiACg2dXgwjYGbA6A0Ivcy1XC7u9rJa64PNzcU0hbDR9ElB/+z2zWp9dDZVY+1IZPOUmxX5k7GBz4caKa6msE63xqAirFS/LRA8480xkThz6JGSbdgYkpiGzZFS3WgKk8s73gjiKNuV44CEm0t98y2+04yPbLcSASXVkGteG51V+sw4TNoyRb+n/bZgA1VKQ86t5dL5YnibCfIOWV921RS3vp82EUDoMBtRTNPCRbIGH5t3RhqOGIvaQ=
  on:
    tags: true
    branch: master
  skip_cleanup: true